### PR TITLE
NvFBC grabber support

### LINKED ISSUE #235: Add Nvidia Frame Buffer Capture (NVFBC and NVIFR) API support please!
Nvidia uses hardware FBC for its own streaming and recording software Expirience. Steam also uses it for streaming to steam link.

They work independant from any API uses in game or sofware. FBC effective for full screen framebuffer capture and IFR for windowed capture, her some details:

NVFBC

Captures the framebuffer (front buffer) without any involvement from OpenGL or Direct3D. 

Effectively a direct copy of the framebuffer irrespective of which application(s) drew it.

It generally only works sensibly in fullscreen mode. If you render in windowed mode and use NVFBC, it is going to capture the entire screen including your desktop and other unrelated windows.

NVIFR

Slightly more complicated and less performant than NVFBC, this can capture a single application.

In my experience this used to be how Steam would stream windowed-mode applications. I have not seen this capture path in a very long time and I am glad because performance was awful whenever it was used.

Here some documentation https://developer.nvidia.com/sites/default/files/akamai/designworks/docs/NVIDIA%20Capture%20SDK%20Programming%20Guide.pdf

http://on-demand.gputechconf.com/gtc/2016/presentation/s6307-shounak-deshpande-get-to-know-the-nvidia-grid-sdk.pdf

Here the capture SDK itself: https://developer.nvidia.com/capture-sdk

ATI also has something similar, but im not very familiar with it, maybe google it.

Anyway, implementation of this will reduce CPU load and performance impact completely, please do this as soon as you can.

### PR DESCRIPTION
**Pull request by maxroehrl**
Adds support for Nvidia framebuffer capture.

It only works with Nvidia graphic cards in Windows.

The downscale factor can be adjusted in percent (1% to 100%).
25% percent is the default value.

Capturing stops when DXVA encrypted content is being played.

Fixes #235 

Annotation 2019-04-06 205515

### CODE REVIEW

**Comment by AndySledge** [comment]
Works perfectly, kudos to you!

**Comment by sblantipodi** [comment]
@psieg  Can one of the admins verify this patch?

**Comment by psieg** [comment]
Thanks! 
Sorry for the delay, I was on vacation. A quick test ran great, I'll need some time to look into the details but I won't be available around easter, so it might take a while, sorry about that.

The magic sequence is taken from a software called LookingGlass? Should we expect this to be revoked in the near future? I guess I'll have to do some research on the license there...

**Comment by psieg** [comment]
ok to test

**Comment by maxroehrl** [comment]
I have replaced the qInfo calls with DEBUG_LOW_LEVEL.

I also think it is not worth the effort to switch the grabber while playing protected content in fullscreen.

Here are two answers from the [Capture SDK FAQ](https://developer.nvidia.com/sites/default/files/akamai/designworks/docs/NVIDIA-Capture-SDK-FAQ.pdf):

Q10) Can I distribute any NVIDIA Capture SDK components to my customers?
A10) No, the NVIDIA Capture SDK is subject to NVIDIA’s Software License Agreement.  Any re-distribution rights will require explicit permission from NVIDIA.

Q11) I have questions about integrating my software with the NVIDIA Capture SDK.  How do I contact support?
A11) Please refer to the Programming Guide and included documentation.  For detailed questions, please contact GRID developer support at GridPublicSupport@nvidia.com.

The software license agreement can be found here:
https://developer.nvidia.com/capture-sdk-software-license-agreement

**Comment by psieg** [comment]
So it seems this is not allowed, but technically possible. The license allows use on Pro GPUs, on which I guess you don't need the magic bytes. Then some people (steam etc) seem to have separate agreements with NVIDIA that allow the use on consumer hardware, which is enforced using these magic bytes.
I guess the only legally safe option is to ask NVIDIA for a such license. Given Prismatik is not competing with ShadowPlay or other NVIDIA products, this might be a possibility.

Now the question is how much this license applies. We would not be shipping the SDK in the binary, nor linking it.  The header itself is also covered by the license though.
If one were to implement this without using a NVIDIA header, could the license violation be shifted to the user running the software, who would have to actively enable the use of the SDK and agree that this violates his license (which he agreed to when installing the driver)?
I'm not a lawyer and I'd rather not be sued by NVIDIA...

**Comment by sblantipodi** [comment]
Sincerely I don't see the problem since prismatik is not competing with anything commercial or from nvidia.
please merge this pull request :)

**Comment by psieg** [comment]
I know, but that doesn't make it legal. I sent an email, let's see what they think.

**Comment by zomfg** [comment]
Maybe if grabbers become dll plugins... but that sounds like work

**Comment by sblantipodi** [comment]
> I know, but that doesn't make it legal. I sent an email, let's see what they think.

imho you will never get a reply, probably there is no one behind that email address.
I wrote them months ago and never get a reply.
give us the option to pirate that license, sincerely I really don't care about nvidia licenses. 
I paid 1300€ for a Geforce, I paid enough to use prismatik on my geforce :D

**Comment by corsarchik** [comment]
Hello, thank you so much for your work with prismatic on windows. Tell me if there is a way to get a 32 bit latest version of prismatic on windows?

**Comment by sblantipodi** [comment]
@psieg did you get a reply from Nvidia?
As I said you, if they don't care answering questions why we should care about a bit that enables a feature? 😁

**Comment by TheAnswer** [comment]
This also fixes g-sync issue #244

**Comment by psieg** [comment]
Unfortunately no reply.
If someone here would be willing to take the risk, we could do a grabber plugin API and that someone else would distribute the NVFBC plugin. Any developer interested?

**Comment by sblantipodi** [comment]
> Unfortunately no reply.
> If someone here would be willing to take the risk, we could do a grabber plugin API and that someone else would distribute the NVFBC plugin. Any developer interested?

@psieg @maxroehrl imho this is not the right way to do it.

simply create an input text to let the user input the magic key. 

don't include it into your software and inser a disclaimer like "if you have the authorization from nvidia, you can enter the key here"
then the user will input the magic key and take the responsability of using that key.

**Comment by sblantipodi** [comment]
@psieg what about my solution?

**Comment by psieg** [comment]
From a licensing perspective, it's not about the key. It's about using nvfbc headers and distributing binaries based on it.
The license doesn't mention the key.
If max (or someone else) is fine with distributing a capture module we can work something out...

Yes, the project needs dev power, and anyone is welcome to help, but licenses are a messy thing and I don't want to be sued. Sorry I can't offer a better solution.

**Comment by sblantipodi** [comment]
@maxroehrl are you still there? what do you think about this? do you see some possible solutions?
I ask you because you are the author of the pull request.

**Comment by maxroehrl** [comment]
The problem are the two header files.

But you can still download it from the issue thread or compile it yourself from my branch.
If there is a new change in Lightpack I can also make a new build with NvFBC support.
I think Jenkins also automatically makes a new build when there are changes in this repo.
If you click on "Show all checks" and "Details" you can see the build artifact.

I dont know if its worth the effort to add grabber plugin support.

**Comment by sblantipodi** [comment]
@maxroehrl 
if there is some change in lightpack where will you publish your build? 

I haven't understood, if psieg commits some new features/bug in the main branch, will this branch be automatically updated? I don't think so, am I wrong?

**Comment by maxroehrl** [comment]
@sblantipodi I think I can create a unofficial release in my fork if the CI does not create one for this pull request automatically.

You can access the builds of the CI [here](https://psieg.de/jenkins/job/Prismatik_Windows/471/).

**Comment by sblantipodi** [comment]
@maxroehrl thanks a billion. I think that a lot of people will appreciate it.
pretty sad to not have "included in the official release".
many people will simply stop using prismatik because "it does not works for games", not everyone uses or read github

**Comment by psieg** [comment]
Prismatik works fine for games. The performance impact is <1 FPS for most scenarios. It doesn't work nicely for the few people who have both LEDs on their screen and a GSync screen.
I'm sorry about that, but I don't want to take the risk.
If you want to, why don't you go host it or maintain a fork?

**Comment by sblantipodi** [comment]
@psieg 
In 2019 gamers uses GSYNC, so no, prismatik does not work in games without the maxroehrl patch.
Really really few gamers have no variable refresh rate monitor today and pretty no one would prefer prismatik to VRR.

I don't want to maintain a fork since I'm not into the project and I know nothing on it.
I was just asking if there is a smarter way to include NvFBC support in prismarik without "breaking the rules".

maxroehrl suggested a way to do it but it isn't the best one for people who don't use github.
if there is no other way, gamers will learn to live without prismatik, some others more lucky, will use the maxroehrl version until they'll find a working build.

guys I'm not complaining, I love this project and I think that you psieg and maxroehrl have done a marvelous work since now.

prismatik is a really really bad ass software and I thank you every time I start it :) love it!
thank you for your time and for your work on it! 

I hope that nvidia will change its stupid mind 💃 
they started "enabling geforce" to 30bit colors, hope that NvFBC will have the same threatment soon.

**Comment by sblantipodi** [comment]
PS: This is how I use prismatik.
https://github.com/sblantipodi/pc_ambilight

loving it every time I use it. on every film (thanks psieg) or games (thanks maxroehrl)
thanks both 💃

**Comment by x-trend1** [comment]
Tell someone, on this version, after turning off the screen, the backlight does not turn on, how can I fix it? On the previous version, everything was fine. And what kind of downscale do I need to put on 1080ti  on 2560x1440, what does it affect?

**Comment by sblantipodi** [comment]
@maxroehrl sad to see this wonderful merge request closed.
hope in "something" different in the future and that nvidia will change its mind in this.

**Comment by maxroehrl** [comment]
@sblantipodi Yeah it's a shame :(
But thanks for all your support everybody!

**Comment by sblantipodi** [comment]
@maxroehrl thanks to you for your great patch and please don't abandon the project, we all need people like you.

**Comment by BlackX777** [comment]
@maxroehrl also heartfelt thanks from me
P.S.: you can still found this pearl its build #471

**Comment by BlackX777** [comment]
[Prismatik.zip](https://github.com/psieg/Lightpack/files/4873062/Prismatik.zip)

**Comment by BlackX777** [comment]
[Prismatik (unofficial) 64bit Setup 5.11.2.27 NvFBC.zip](https://github.com/psieg/Lightpack/files/8754059/Prismatik.unofficial.64bit.Setup.5.11.2.27.NvFBC.zip)

**Pull request closed without merging**
