### PR TITLE
Enable C++11 mode for GCC and Clang.

### PR DESCRIPTION
**Pull request by dreamer-dead**
This should allow to compile the project with Clang and GCC.
PTAL.

### CODE REVIEW

**Comment by dreamer-dead** [comment]
Offtopic: @psieg, what do you think about merging our forks?
Some time ago I commited few changes for Lightpack to make it better (as I think).
Some of them are pretty specific, like using GTest instead of QTest (QTest is a horrible library for tests, IMHO). But there are a bunch of fixes and some refactorings.

**Comment by psieg** [comment]
Do you know a good way of comparing all the changes? PR against master? Rebase your master on mine?

**Comment by dreamer-dead** [comment]
That will depends on changes in our forks.
If we changed different things, rebase or merge can be done easily.
But if we touched the same code, it will be a nightmare.

I suppose that I can extract separate parts of my changes or fixes and then create PRs to your fork.
If you already enabled Travis CI builds, it will test the compilation.
Do you use a Windows based CI build? For example, AppVeyor?

**Comment by psieg** [comment]
Yeah. I'll need to do some configuration to get it to build your PRs autmatically, but that sounds good :+1:

**Pull request merged**
