### PR TITLE
Added simplified Chinese translation for zh-cn.ts

### PR DESCRIPTION
**Pull request by Joyist2021**
Added simplified Chinese translation for zh-cn.ts，In order to better promote in the Chinese community.

### CODE REVIEW

**Comment by Joyist2021** [comment]
Oh! I don't have a compilation environment, please help to verify, thank you very much!

**Comment by Joyist2021** [comment]
> 管理员可以验证此补丁吗？



> Can one of the admins verify this patch?

Oh! I don't have a compilation environment around me, please help to verify, thank you very much!

**Comment by psieg** [comment]
All good, thank you!

**Comment by Bohan-Song** [comment]
How to use ?怎么使用啊?

**Comment by Bohan-Song** [comment]
> Added simplified Chinese translation for zh-cn.ts，In order to better promote in the Chinese community.

求教,怎么使用

**Comment by psieg** [comment]
Use [this version](https://github.com/psieg/Lightpack/files/8028333/Prismatik.unofficial.64bit.Setup.5.11.2.31.exe.zip) until the next release is out.

**Pull request merged**
