### PR TITLE
macos deprecations

### PR DESCRIPTION
**Pull request by zomfg**
Small things here and there.
And an ugly hack to circumvent qmake's [unfixed limitation](https://bugreports.qt.io/browse/QTBUG-54791). This is for Xcode only though, so it won't break CI builds.

### CODE REVIEW

**Comment by psieg** [comment]
LGTM, just assuming this works
ok to test

**Comment by zomfg** [comment]
Are you the one building the mac release? And if yes what versions of os/xcode/sdk do you use?
The reason I'm asking is because I only saw windows and linux builds on your jenkins setup

**Comment by zomfg** [comment]
Looks like by default it uses old-ish stuff. Could you bump it to [10.14](https://docs.travis-ci.com/user/reference/osx/#xcode-101)?
That's what I did the majority of my testing on so should be safe enough.

**Comment by psieg** [comment]
done

**Comment by zomfg** [comment]
cool
we'll get dark mode automatically through Qt and be able to properly ask permissions for privacy related things, like sound (funny thing, you can record the screen all day without telling anyone, but you need to ask for audio devices...)

**Pull request merged**
