### PR TITLE
Introduce Dithering to increase color resolution.

### PR DESCRIPTION
**Pull request by Womifa**
When using color temperature correction the color resolution is reduced. By introducing dithering some of that resolution can be recovered. However, it can create flickering.

### CODE REVIEW

**Comment by zomfg** [comment]
I haven't seen this in action yet, but I think it's in a wrong place: what about non-Adalight devices?
somewhere here should be better
https://github.com/psieg/Lightpack/blob/772d0be12124bd15da7b18af393c127b62ac23ca/Software/src/GrabManager.cpp#L424-L429
this will cover 2 of the 3 ways of changing the color temp

**Comment by Womifa** [comment]
The dithering code should have access to the final bytes that will be sent to the LEDs, thats why I put it into the Adalight Code.

I have merged the dithering code into the function responsible for white point adjustment. This relies on the knowledge that the bytes that will be sent to the LEDs are the eight most significant bits calculated in applyColorModifications(). So from a software architecture perspective this is not great, but it should be quite compatible.

**Comment by psieg** [comment]
In fact Lightpack does use 12 bits:

https://github.com/psieg/Lightpack/blob/7aa0be414e1eb28ed03c660f382d987f20927bbd/Software/src/LedDeviceLightpack.cpp#L111-L120

I would suggest to put it in a dedicated function in AbstractLedDevice and then call that from all devices that send only 8 bits, what do you think?

**Comment by Womifa** [comment]
I put the dithering algorithm in a dedicated function that is called in each LED device class with the respective color resolution of the devices. I also tried to make the dithering algorithm be more precise, not sure though whether that worked.

**Comment by psieg** [comment]
Thanks! I'll test in on the weekend

**Comment by psieg** [comment]
Worked fine with my Lightpacks, I didn't notice flickering. I'll merge the cleaned-up #394 instead of this one to avoid the unnecessary commits.

Thank you :)

**Pull request closed without merging**
