### PR TITLE
Implement LightpackCommandLineParser class.

### PR DESCRIPTION
**Pull request by dreamer-dead**
Hi!
Here is a part of my fork, it does the following things:
- Add alternate way to set debug level (--debug=level).
- Handle --help and --version command switches.
- Add unit-tests for LightpackCommandLineParser class.

Also I enabled C++11 mode for tests.
PTAL.

### CODE REVIEW

**Comment by psieg** [comment]
ok to test

**Comment by dreamer-dead** [comment]
Does the Jenkins bot compile and run unit tests for Prismatic?
I don't see a build log or test output for it.
If not, shouldn't we add this step?

**Comment by psieg** [comment]
It does, but I'm not entirely sure the config is right. Click on "show all checks" below to get to the jenkins log. Note the jenkins script does not run tests ATM

**Comment by dreamer-dead** [comment]
Oh, I see that it compiles the tests, missed that at the first look.

**Comment by psieg** [comment]
Thanks :)

**Pull request merged**
