### PR TITLE
color temperature settings

### PR DESCRIPTION
**Pull request by zomfg**
(Serves as a foundation for implementing Night Light support. I'll come back to that later)
**Color Temperature**
- adds (fixed) color temperature/gamma settings to "Mode" page (under "Apply screen color modification")
- adds 3-in-1 helper slider to "Coef Configuration" page to adjust white point coefs using color temperature

Basically this emulates a gamma ramp that you would otherwise have with f.lux/redshift and applies it to colors in the same place in the `GrabManager`. It's just not dynamic.
So for ex, if you use 4000K and 0.8 gamma in redshift, you should see similar result on the LEDs by dialing in same CT/gamma in Prismatik.
I made these 2 settings (screen color / color temp) exclusive so there's no conflicts/double gamma ramp application.

-------------------

...back to **Night Light** discussion
I made a [Night Light wrapper .lib](https://github.com/zomfg/NightLightLibrary/blob/master/NightLight.h) that knows when NL is on/off and with what color temperature (which would be applied through the above).
The implementation in Prismatik currently looks [like this](https://github.com/zomfg/Lightpack/commit/d181c60e8c644b7b35dba0cbe71af48d74eecddc).
Right now I'm not sure how to package it so it's easily integrated into Prismatik project.
Since it's a general purpose lib and not specific to Prismatik (although some bits were made based on Prismatik needs) I want to avoid to add the whole thing to `Lightpack.sln`.
My guess is I need to set up pre-built releases and add it to Lightpack project the same way `bass` and `openssl` are, so it'll be an optional dependency as well. Do I need to mess with other files than `build-vars.prf` ? (I'm not familiar with qmake process)
If you have any suggestions...

**Edit**: I made [a v1 release](https://github.com/zomfg/NightLightLibrary/releases/tag/v1.0) with a `.lib` and `.h` if you want to try.

### CODE REVIEW

**Comment by psieg** [comment]
ok to test

**Comment by psieg** [comment]
thanks, I'll try it tomorrow

**Comment by psieg** [comment]
Thank you :)
This looks great in general, just a few nits:
- You should expand CT to Color Temperature and maybe add a sentence to the instruction text like "use CT to choose a color temperature and RGB to match to your screen".
- The GlobalColorCoefPage is somewhat crammed now. Feel free to increase the size of the Wizard.
- You have some stray commits from the master branch there. Ideally, create a PR that has only the actual change commits in it.  Otherwise I'm just going to squash merge, no problem.

Now about night light. IIUC the library reads the configuration, so the idea is to grab plain data and emulate what we think night light is doing based on its configuration using the new settings.

Yes the cleanest thing would be a lib to optionally include in the build. You'd have a variable in build-vars, which is read in src.pro to determine whether to include some files and add linker flags. If you grep for BASS_SOUND_SUPPORT it should be a good template.

**Comment by psieg** [comment]
I don't have too much experience with external libs and I'd rather not have to add bond and boost to the build process for Prismatik.
Is it possible to have the release of NightLightLibrary being a header file that doesn't include boost/bond and a lib/dll that either includes them or can load them from dlls lying next to it?

**Comment by zomfg** [comment]
> * You should expand CT to Color Temperature and maybe add a sentence to the instruction text like "use CT to choose a color temperature and RGB to match to your screen".

Yeah, wasn't sure about the text, I'll change it.

> * The GlobalColorCoefPage is somewhat crammed now. Feel free to increase the size of the Wizard.

Indeed, I'll try that.

> * You have some stray commits from the master branch there. Ideally, create a PR that has only the actual change commits in it.  Otherwise I'm just going to squash merge, no problem.

I think I was behind master and merged it before the push to be sure to not get the infamous ❌ 
Ok, I'll leave it as is next time.

> Now about night light. IIUC the library reads the configuration, so the idea is to grab plain data and emulate what we think night light is doing based on its configuration using the new settings.

Pretty much, yes. But I'm confident enough in my reverse engineering to say that there isn't much guessing left, and I was getting pretty consistent results on my system.

> Yes the cleanest thing would be a lib to optionally include in the build. You'd have a variable in build-vars, which is read in src.pro to determine whether to include some files and add linker flags. If you grep for BASS_SOUND_SUPPORT it should be a good template.

Ok thanks, I'll check that out.

> I don't have too much experience with external libs and I'd rather not have to add bond and boost to the build process for Prismatik.
> Is it possible to have the release of NightLightLibrary being a header file that doesn't include boost/bond and a lib/dll that either includes them or can load them from dlls lying next to it?

Wait, are you talking about adding bond/boost full libraries? Because my intention was to just add their headers (maybe putting them together with `NightLightLibrary.h` so it's in the same include path).
And ideally, yeah, I'd like the header to be as independent as possible in its final form, but I'm not sure how to get there. I'll try some stuff...

**Comment by zomfg** [comment]
I left "CT" next to the slider due to size, but I referenced it in the text above, and there is a tooltip on hover just in case.

**Comment by zomfg** [comment]
> Is it possible to have the release of NightLightLibrary being a header file that doesn't include boost/bond and a lib/dll that either includes them or can load them from dlls lying next to it?

[This](https://github.com/zomfg/NightLightLibrary/releases/tag/v1.1) seems to work.
On Prismatik's side the implementation stays the same, just uses a different class name from [before](https://github.com/zomfg/Lightpack/commit/d181c60e8c644b7b35dba0cbe71af48d74eecddc).

**Comment by psieg** [comment]
Thank you!

**Pull request merged**
