### PR TITLE
Expert tab

### PR DESCRIPTION
**Pull request by zomfg**
So Expert tab is shown like the others.
- It was half Experimental half Expert in the code so I stuck with Expert
- removed the expert mode setting
- ping Lightpack is now hidden
- added "open logs" button (and I remembered the tab order for once...)
- added tooltips with defaults from `SettingsDefault`, I was going to do blue buttons, but the layout is such that you'd need to redo the whole thing so I left it
    - caveat: the default tooltip is from the top groupbox for the API part, so if you don't hover exactly over a nested API field you'd see the top tooltip
- I left this bit in disabled state, not sure if useful
https://github.com/psieg/Lightpack/blob/772d0be12124bd15da7b18af393c127b62ac23ca/Software/src/SettingsWindow.cpp#L533-549
- still not sure about the experimental side of the thing, everything is enabled by default, but you did not even know it before...
   - I'd disable the API by default
   - and "send data only if changed" as it messes with UDP stuff and some Adalight firmwares (mostly in chinese kits)

### CODE REVIEW

**Comment by zomfg** [comment]
- disabled
- but they would keep it when this is OFF too... :p UDP devices do both, depending on the timeout setting: infinite (`255`) would keep last frame, and anything else (`<255`) would "release" the device to display whatever (an onboard animated moodlamp usually). But now I see here and there adalight sketches with built-in timeouts like in this [recent example](https://github.com/psieg/Lightpack/issues/380#issuecomment-677850031), or [here](https://www.youtube.com/watch?v=c97Or8EZNnE) where people think it's Prismatik that shuts everything off. So imo defaulting to false is safer here. The only benefit of having it is bandwidth bottlenecks, but it'll only help with very slow scenes anyway...
- well people that never saw the expert tab never saw the message, and those who did, probably switched by now, yeah, it should be safe to remove I think (it sucks to not have some kind of analytics)

**Comment by psieg** [comment]
Hm. I kind of agree with your reasoning, but at the same time I would prefer to be resource efficient. Do you think it makes sense to ask this question at device setup instead?
It seems like a device (rather than profile) specific setting, though migrating this on existing setups would be a pain...

So I guess I'm fine with flipping the default (don't forget the tooltip :P )

**Comment by zomfg** [comment]
Yeah yeah, the option is still there and resource conscious users are more likely to find it than others, just less confusion for turnkey people. If it's not pain to add it to the wizard, why not, just not _instead_ of having it here.
Not having it in `Device` isn't the worst I'd say, it being in `Grab` while applying it to lamps/soundviz is weird yeah!

flipping (the tooltips are there including this checkbox, unless you meant something else)

**Comment by psieg** [comment]
I meant changing the "Default: X" part of the tooltip, but actually it's an argument, so... I didn't figure out how to get the tooltip to show up though

**Comment by zomfg** [comment]
just hovering mouse over label/input should work
image

**Comment by psieg** [comment]
Well, not on Windows....

**Comment by zomfg** [comment]
oh
here's on a master build
image

**Comment by psieg** [comment]
ah. I was confusing tooltip with whatsThis. The other elements have whatsThis's. Thanks for checking

**Pull request merged**
