### PR TITLE
night light support

### PR DESCRIPTION
**Pull request by zomfg**
I think we are ok to try building this.
I did the qmake bits (`build-vars` and `src.pro`) and `GrabManager`'s `#ifdefs`.
I [re-released](https://github.com/zomfg/NightLightLibrary/releases/tag/v1.1) NightLight library without external includes and with debug/release builds.
I'm able to build first try after (re-)generating the `sln` (but my VS knows about bond and boost so that's the doubt I have at the moment).

Now, as you can see this branch too, has a ton of stray merge commits, this dates from a while ago and it's based on the color-temperature branch that had them, sorry :(
Files of interest are:

- `src/src.pro`
- `src/GrabManager.[ch]pp`
- `build-vars.prf.default`
- `src/SettingsWindow.ui` (help text)

### CODE REVIEW

**Comment by psieg** [comment]
ok to test

**Comment by psieg** [comment]
The mess with the commits might be my fault. I may have force pushed the master branch at some point...

**Comment by psieg** [comment]
This breaks the build with VS2013, which doesn't recognize noexcept. Also the library is built with VS2015.

Moving to a newer (and free) VS version should be fine, except the openssl builds I use don't work with VS2015 (that is, i's runtime version) as they are compiled for 2013. I'll have to dig into this.

**Comment by zomfg** [comment]
Oh, right, I used c++14 in VS2017 for the lib.

Well FWIW, Prismatik seems to build fine with a c++17 switch in VS, so if it's possible to move in that direction that would be swell...
Otherwise I could try `#define`ing `noexcepts` depending on `_MSC_VER` or something.

**Comment by psieg** [comment]
I tried using this (Installed vs2017 and downloaded your release.
I got some exceptions while debugging and a crash once when changing the night light settings, but I can't reproduce.
The important thing: it seems to work :)

I'm not sure whether or not it should keep watching the settings even if it is not enabled at startup (Turn Night light off, don't schedule, then start Prismatik and then turn it on).

**Comment by psieg** [comment]
bond::CoreException I think, but I could just continue and it was caught apparently.
Not sure about the crashing one ("application triggered a breakpoint").
I'll have to fix the dependency problems first though...

**Comment by zomfg** [comment]
I made [another build](https://github.com/zomfg/NightLightLibrary/releases/tag/v1.2) to try:
- (more) bond exceptions should be catched
- reported color temp to Prismatik should be more consistent in some cases

**Comment by psieg** [comment]
merged #219, thank you, this is a much-requested feature :)

**Comment by zomfg** [comment]
Yeah, I needed it myself :p 
Do you have a date in mind for Prismatik release? I'm still tweaking the lib a bit, so I'll probably do another build soon

**Comment by psieg** [comment]
No clear plan. I want to add a checkbox for the screen off thing and I won't have a lot of time during the holidays. So Mid January roughly...

**Comment by zomfg** [comment]
fyi I pushed [another release](https://github.com/zomfg/NightLightLibrary/releases/tag/v1.3) since then

**Pull request closed without merging**
